// examples/vue-chat/src/App.vue
<script setup lang="ts">
import { ref, nextTick } from 'vue';
import { useSlotmux } from './use-slotmux';

type Message = { role: 'user' | 'assistant'; content: string };

const { meta, utilization, totalTokens, user, assistant, build } = useSlotmux();
const messages = ref<Message[]>([]);
const input = ref('');
const chatEnd = ref<HTMLDivElement | null>(null);

async function send() {
  const text = input.value.trim();
  if (!text) return;

  messages.value.push({ role: 'user', content: text });
  input.value = '';

  user(text);
  await build();

  // Simulate assistant response (replace with real API call)
  const reply = `Echo: ${text}`;
  assistant(reply);
  await build();

  messages.value.push({ role: 'assistant', content: reply });

  await nextTick();
  chatEnd.value?.scrollIntoView({ behavior: 'smooth' });
}
</script>

<template>
  <div class="container">
    <h1>Slotmux Vue Chat</h1>

    <div v-if="meta" class="status">
      <span>Tokens: {{ totalTokens }}</span>
      <span>Utilization: {{ (utilization * 100).toFixed(1) }}%</span>
      <span>Build: {{ meta.buildTimeMs }}ms</span>
    </div>

    <div class="messages">
      <div
        v-for="(m, i) in messages"
        :key="i"
        :class="['message', m.role]"
      >
        <span class="bubble">{{ m.content }}</span>
      </div>
      <div ref="chatEnd" />
    </div>

    <form @submit.prevent="send" class="input-row">
      <input v-model="input" placeholder="Type a message..." />
      <button type="submit">Send</button>
    </form>
  </div>
</template>

<style scoped>
.container {
  max-width: 640px;
  margin: 0 auto;
  padding: 2rem;
  font-family: system-ui, sans-serif;
  display: flex;
  flex-direction: column;
  height: 100vh;
}

.status {
  display: flex;
  gap: 1rem;
  padding: 0.5rem 1rem;
  background: #f5f5f5;
  border-radius: 8px;
  font-size: 0.85rem;
  color: #666;
}

.messages {
  flex: 1;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 1rem;
  margin: 1rem 0;
}

.message {
  margin-bottom: 0.75rem;
}

.message.user {
  text-align: right;
}

.bubble {
  display: inline-block;
  padding: 0.5rem 0.75rem;
  border-radius: 12px;
  max-width: 80%;
}

.message.user .bubble {
  background: #42b883;
  color: #fff;
}

.message.assistant .bubble {
  background: #f0f0f0;
  color: #000;
}

.input-row {
  display: flex;
  gap: 8px;
}

.input-row input {
  flex: 1;
  padding: 0.75rem;
  border-radius: 8px;
  border: 1px solid #ddd;
  font-size: 1rem;
}

.input-row button {
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  border: none;
  background: #42b883;
  color: #fff;
  font-size: 1rem;
  cursor: pointer;
}
</style>

// examples/react-chat/src/App.tsx
import { useRef, useState, useCallback, type FormEvent } from 'react';
import { reactiveContext } from 'slotmux/reactive';
import {
  useReactiveContextMeta,
  useReactiveContextUtilization,
  useReactiveContextBuildError,
} from '@slotmux/react';

const rctx = reactiveContext({
  model: 'gpt-5.4-mini',
  preset: 'chat',
  reserveForResponse: 4096,
  charTokenEstimateForMissing: true,
});

rctx.system('You are a helpful assistant.');

type Message = { role: 'user' | 'assistant'; content: string };

function StatusBar() {
  const meta = useReactiveContextMeta(rctx);
  const utilization = useReactiveContextUtilization(rctx);
  const error = useReactiveContextBuildError(rctx);

  if (error) {
    return <div style={{ color: 'red', padding: '0.5rem' }}>Build error: {String(error)}</div>;
  }

  if (!meta) return null;

  return (
    <div
      style={{
        display: 'flex',
        gap: '1rem',
        padding: '0.5rem 1rem',
        background: '#f5f5f5',
        borderRadius: 8,
        fontSize: '0.85rem',
        color: '#666',
      }}
    >
      <span>Tokens: {meta.totalTokens}</span>
      <span>Utilization: {(utilization * 100).toFixed(1)}%</span>
      <span>Build: {meta.buildTimeMs}ms</span>
      <span>
        Slots:{' '}
        {Object.entries(meta.slots)
          .map(([name, s]) => `${name}(${s.usedTokens})`)
          .join(', ')}
      </span>
    </div>
  );
}

export function App() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const endRef = useRef<HTMLDivElement>(null);

  const handleSubmit = useCallback(
    async (e: FormEvent) => {
      e.preventDefault();
      if (!input.trim()) return;

      const userMsg: Message = { role: 'user', content: input.trim() };
      setMessages((prev) => [...prev, userMsg]);
      setInput('');

      rctx.user(userMsg.content);
      await rctx.build();

      // Simulate an assistant response (replace with real API call)
      const reply = `Echo: ${userMsg.content}`;
      rctx.assistant(reply);
      await rctx.build();

      setMessages((prev) => [...prev, { role: 'assistant', content: reply }]);

      setTimeout(() => endRef.current?.scrollIntoView({ behavior: 'smooth' }), 50);
    },
    [input],
  );

  return (
    <div
      style={{
        maxWidth: 640,
        margin: '0 auto',
        padding: '2rem',
        fontFamily: 'system-ui, sans-serif',
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
      }}
    >
      <h1 style={{ marginBottom: '0.5rem' }}>Slotmux React Chat</h1>
      <StatusBar />

      <div
        style={{
          flex: 1,
          overflowY: 'auto',
          border: '1px solid #ddd',
          borderRadius: 8,
          padding: '1rem',
          margin: '1rem 0',
        }}
      >
        {messages.map((m, i) => (
          <div
            key={i}
            style={{
              marginBottom: '0.75rem',
              textAlign: m.role === 'user' ? 'right' : 'left',
            }}
          >
            <span
              style={{
                display: 'inline-block',
                padding: '0.5rem 0.75rem',
                borderRadius: 12,
                background: m.role === 'user' ? '#646cff' : '#f0f0f0',
                color: m.role === 'user' ? '#fff' : '#000',
                maxWidth: '80%',
              }}
            >
              {m.content}
            </span>
          </div>
        ))}
        <div ref={endRef} />
      </div>

      <form onSubmit={handleSubmit} style={{ display: 'flex', gap: 8 }}>
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Type a message..."
          style={{
            flex: 1,
            padding: '0.75rem',
            borderRadius: 8,
            border: '1px solid #ddd',
            fontSize: '1rem',
          }}
        />
        <button
          type="submit"
          style={{
            padding: '0.75rem 1.5rem',
            borderRadius: 8,
            border: 'none',
            background: '#646cff',
            color: '#fff',
            fontSize: '1rem',
            cursor: 'pointer',
          }}
        >
          Send
        </button>
      </form>
    </div>
  );
}
